openapi: 3.0.0
paths:
  /events:
    post:
      summary: Create an Event
      description: Create an Event
      operationId: 'createEvent'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../../../../../../schemas/com/github/potjerodekool/openapi/demo/model/event.yml'
      responses:
        '201':    # status code
          description: Event created
          content:
            application/json:
              schema:
                $ref: '../../../../../../../schemas/com/github/potjerodekool/openapi/demo/model/createResponse.yml'
    get:
      summary: Returns a list of events.
      description: List of events.
      operationId: 'getEvents'
      responses:
        '200':    # status code
          description: A JSON array of events
          content:
            application/json:
              schema:
                $ref: '../../../../../../../schemas/com/github/potjerodekool/openapi/demo/model/eventsResponse.yml'
