openapi: 3.0.2
paths:
  /activities:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../../../../../../schemas/com/github/potjerodekool/spafdeling/api/model/activityListResponse.yml'
  /activities/{activityId}:
    patch:
      operationId: 'patchActivityById'
      parameters:
        - in: path
          name: activityId
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../../../../../../schemas/com/github/potjerodekool/spafdeling/api/model/activityPatch.yml'
      responses:
        '204':
          description: No content

