openapi: 3.0.0
info:
  title: Sp afdeling API
  description: Sp afdeling API
  version: v0.0.1
  license:
    name: 'test'
    url: 'https://google.com'
servers:
  - url: http://api.example.com/v1
    description: Production
