openapi: "3.0.0"
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "../../../../../schemas/io/swagger/petstore/api/model/pets.yaml"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../../../../../schemas/io/swagger/petstore/api/model/Error.yaml"
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../../../../../schemas/io/swagger/petstore/api/model/Error.yaml"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "../../../../../schemas/io/swagger/petstore/api/model/Pet.yaml"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "../../../../../schemas/io/swagger/petstore/api/model/Error.yaml"